### PR TITLE
Fix/api calls

### LINKED ISSUE #9: Set Timeout for History pushes
add set time out to heach push to history

### LINKED ISSUE #36: Add Clear Game Function
- [x] add function in app
- [x] add corresponding fetch request

### PR DESCRIPTION
**Pull request by holladayian**
## Description
This branch cleans up the api calls, and then test's that they work. From here, our game should be hooked up and ready to run sockets. 

## Context
Without sockets, the guesser isn't able to live update to the gamepage (without doing something crazy like continuously running fetch calls), hence the necessity of sockets.

## Where To Start
APICalls.js and App.ja

## Screenshots (if applicable):
n/a

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] The correct data is being sent to/from the server
- [x] DOM still updates when needed

## Relevant Tickets
Fixes #36 
#23 
#24 
Fixes #9 

## Tags
@Chriscastanuela 
@GreyMatteOr 

## Questions or Notes (if applicable):
n/a

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -11,43 +11,74 @@ export class App extends Component{
...
-      History.push('/gamepage');
-    } else if (History[History.length -1] !=='/') {
-      History.push('/');
+    if (this.state.numPlayers > 1 && !this.state.word && History[History.length -1] !== '/word-selector') {
+      window.setTimeout(() => History.push('/word-selector'), 1);
+    } else if (this.state.numPlayers > 1 && this.state.word && History[History.length -1] !== '/gamepage') {
+      
+      window.setTimeout(() => History.push('/gamepage'), 1);
+    } else if (History[History.length -1] !== '/') {
+      window.setTimeout(() => History.push('/'), 1);
```
Comment (GreyMatteOr) [inline src/App.js:75]: I would like to document why this is here:

We were getting some `multiple rendering` errors. SetTimeout gives necessary async timing to avoid these conflicts. We should make a low priority issue to perhaps clean up this.... somewhat smelly code. I wish I knew how, it may be an adventure.

**Review by GreyMatteOr — APPROVED** [review]
Cool! I just want to get there.

**Review by Chriscastanuela — APPROVED** [review]
Love it, no complaints
